# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  jenkins:
    build: .
    ports:
      - '80:8080'
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=bitnami
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local